/**
 * *****************************************************************************
 * Copyright (c) 2008-2015 LogiCoy, Inc. All rights reserved. This program and
 * the accompanying materials are made available under the terms of LogiCoy
 * License v1.0 which accompanies this distribution, and is available at
 * https://www.logicoy.com
 *
 * Contributors: LogiCoy, Inc. - initial API and implementation
 * ****************************************************************************
 */
/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/security/AccountDetailsServiceImpl-spring3.p.vm.java
 */
package com.logicoy.bpelmon.security;

import java.text.SimpleDateFormat;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.web.servlet.handler.HandlerInterceptorAdapter;

/**
 *
 * @author Paramjeet
 */
@Controller
public class LogoutInterceptor extends HandlerInterceptorAdapter {

	private static final Logger LOGGER = Logger.getLogger(LogoutInterceptor.class);

	@Override
	public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler)
			throws Exception {

		LOGGER.info("Inside logout intercepter.. ");
		SecurityContextHolder.getContext().getAuthentication();
		HttpSession session = request.getSession(false);

		if (session.getAttribute("loggingLogged") != null) {
			LOGGER.info("Sending file upload data to elastic search engine...start");
			new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			LOGGER.info("Sending file upload data to elastic search engine...success");
		}
		return true;
	}

}
